# Generated by Django 5.0.2 on 2024-03-04 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productcategory',
            fields=[
                ('productcategory_name', models.CharField(max_length=100)),
                ('productcategory_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productprice', models.IntegerField()),
                ('productname', models.CharField(max_length=100)),
                ('productid', models.IntegerField()),
                ('productcategory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.productcategory')),
            ],
        ),
    ]
